### ISSUE TITLE
don't show a list of hidden windows when alt-tabbing

### ISSUE THREAD

**Issue by mercengila** [ViliamKovac1223/dwm-ViliamKovac1223-build#5]
Recently i just used this patch and combined it with awesomebar patch which has a function to hide windows, everything works fine except a bit of weird workflow, it would be better not to show the list of hidden windows when alt-tabbing.

anyway this patch is awesome

**Comment by ViliamKovac1223** [comment]
Hi, I use awesomebar patch too and I made alt-tab patch to work with it, but because not everyone is using awesomebar and they might use alt-tab by default there is no "co-operation" of these patches. If you want your alt-tab to work nicely with awesombar please uncomment all lines (currently 3) with this comment on them `uncomment if you're using awesomebar patch`. After this (and recompiling of course) everything should work as intended.

example: 
from this: `/* if (HIDDEN(c)) continue; uncomment if you're using awesomebar patch */`
to this: `if (HIDDEN(c)) continue; /* uncomment if you're using awesomebar patch */`

I hope everything will work for you after this. If not I'd look into if you have patched everything correctly.

**Comment by mercengila** [comment]
Ah, I didn't read the code carefully, thanks for the help.

**Comment by mercengila** [comment]
is this patch compatible with alpha patch? i tried combining them and it crashed DWM when alt-tabbing

**Comment by ViliamKovac1223** [comment]
No this patch is not compatible with alpha patch currently.
